#ifndef RFMGMT_COMMON_H_
#define RFMGMT_COMMON_H_

#define RFMGMT_VERSION        "01.00"

enum {
  RFMGMT_TIMER_FREE_CACHE = 0,
  RFMGMT_TIMER_CHECK_LOGS,
  RFMGMT_TIMER_CHECK_NET_ALIVE,
  RFMGMT_TIMER_DATA_SERVER_SYNC_HEARTBEAT,
  RFMGMT_TIMER_LOAD_DATA_UPLOADER,
  RFMGMT_TIMER_LOAD_DATA_RECORDER,
  RFMGMT_TIMER_CHECK_UPLOAD_HANG,
  RFMGMT_TIMER_CHECK_SD_CRASH,
  RFMGMT_TIMER_SAVE_INDEX_FILE,

  __RFMGMT_TIMER_MAX,
};

#endif  // RFMGMT_COMMON_H_
