#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"
echo "$BUTTON pressed for $SEEN seconds" > /dev/console

wnc_test=/tmp/wnc_test
[ -f $wnc_test ] && {
	echo "test reboot" > /dev/console
	for file in /dev/pts/*; do
		echo "test reboot" > $file
	done
	exit 0
}

if [ "$SEEN" -lt 1 ]
then
	
        echo "REBOOT" > /dev/console
        sync
        reboot
elif [ "$SEEN" -gt 5 ]
then
        echo "FACTORY RESET" > /dev/console
        mtd -r erase rootfs_data
fi
